<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>



    <ItemGroup>
      <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.13.0" />
      <PackageReference Include="MetadataExtractor" Version="2.9.3" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
      <PackageReference Include="photo.exif" Version="1.1.16" />
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0" />
      <PackageReference Include="Pomelo.EntityFrameworkCore.MySql.Design" Version="1.1.2" />
      <PackageReference Include="SSH.NET" Version="2025.1.0" />
    </ItemGroup>



    <ItemGroup>
      <Folder Include="Configuration\" />
      <Folder Include="IoEngines\MoveFiles\" />
      <Folder Include="IoEngines\Renaming\" />
    </ItemGroup>

</Project>
