<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latestmajor</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\PhotoLibrarizer.Engines\PhotoLibrarizer.Engines.csproj" />
    </ItemGroup>


    <ItemGroup>
      <PackageReference Include="Mono.Posix.NETStandard" Version="1.0.0" />
    </ItemGroup>



</Project>
